### ISSUE TITLE
npx cap sync ios fails

### ISSUE THREAD

**Issue by santosbj** [jayp0521/capacitor-firebase-auth#6]
Hi, 

when i try to sync for ios, got error:

`Updating iOS native dependencies with pod install - failed!
 update ios - failed!
[error] Analyzing dependencies
        [!] No podspec found for JaybabuCapacitorFirebaseAuth in ../../node_modules/@jaybabu/capacitor-firebase-auth`

**Comment by santosbj** [comment]
Hi,

Fix the file 'CapacitorFirebaseAuth.podspec' renaming to 'JaybabuCapacitorFirebaseAuth.podspec', and inside that file, must change the name;

` Pod::Spec.new do |s|
    s.name = 'JaybabuCapacitorFirebaseAuth'`

**Comment by jayp0521** [comment]
Hey, 

I just saw this. Facing this issue too. Will fix it today

**Comment by jayp0521** [comment]
https://github.com/jayp0521/capacitor-firebase-auth/commit/44dd069d818dd8d52b642dfef987d27efbce8755

Testing it out

**Comment by jayp0521** [comment]
Thanks for the fix. Working now: https://github.com/jayp0521/capacitor-firebase-auth/commit/44dd069d818dd8d52b642dfef987d27efbce8755
